apiVersion: apps/v1
kind: Deployment
metadata:
  name: meltano-ui-deployment
  labels:
    app: meltano-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meltano-ui
  template:
    metadata:
      labels:
        app: meltano-ui
    spec:
      containers:
      - name: meltano-ui
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        command: ["meltano", "--log-level=debug", "ui"]
        env:
        - name: MELTANO_DATABASE_URI
          value: "postgresql://postgres:postgres@postgresql.meltano:5432/meltano?sslmode=disable"
