kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-scheduler-service-account
  labels:
    tier: airflow
    component: scheduler
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
