apiVersion: v1
kind: Secret
metadata:
  name: meltano-env
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
data:
  database-uri: {{ .Values.meltano.database_uri | b64enc | quote }}
  env-file: {{ .Values.meltano.b64_env_file | quote }}
