# Default values for meltano.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "meltano/meltano"
  tag: "latest"

meltano:
  database_uri: "sqlite:///$MELTANO_PROJECT_ROOT/.meltano/meltano.db"

ingress:
  enabled: false
  annotations: {}
  path: "/"
