{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meltano-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
        - backend:
            service:
              name: meltano-ui
              port:
                name: http
          {{- if $.Values.ingress.path }}
          path: {{ $.Values.ingress.path }}
          {{- end }}
          pathType: "ImplementationSpecific"
{{- end }}