apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-webserver
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/airflow"
        backend:
          service:
            name: airflow-webserver
            port:
              number: 80
